server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Setup standard config for React Router
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fallback to index.html for Single Page Applications (React Router)
        try_files $uri $uri/ /index.html;
    }

    # error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
