name: Deploy ERP to Windows Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy API to Server
    
    # พระเอกของเรา! เปลี่ยนมารันบนเครื่อง Server ของคุณเองโดยตรง 
    runs-on: self-hosted

    steps:
      - name: Run Deploy Command on Windows Server
        run: |
          cd C:\Users\Administrator\Documents\GitHub\erp_project
          git pull origin main
          npm install
          npm run build
          npx pm2 restart erp_backend
          npx pm2 save
